#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

cancel = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IERlPQskUAAACKklEQVRIx7WUwWoUQRCGv541"
    "GDTZ9AZBCSGsRAIiSsc3mCfIPsLOE2TzBMGTxzVPMPMGa46e1ieQQRFZSGIIAUkQpi+KHjLl"
    "YZZJ987EnSBOnbr6r7/rr6op+MdP1Tlfdumxg1G6OIsl5ZC3H04bEBjDvurVvybv2UvTvxC8"
    "0GqfwZyc38irj7aW4LlmjGkgOyX8ZCsEzzRjZZoVTlLCz9YjeKpVs9fLLCT8YgFaxfnBa+kJ"
    "t7BHLH5/BxAAbBkZeNdWtiXxPIlsi/U8gy1TEsgwxzGbh5N0EuVJ6Ukm0STNw9y6ONmf1mCz"
    "y1dHnVXh0bTXmzF9IDmOivMTI2O0g318fBpA7qsvw+E4kkTKcDhKJXSxeQ8CkB03satdt9gn"
    "0Unknq92PRE7oGAj89KC5Cyq791GIcmRe9ZRsC4VZHJeQ7E+Gw6cq4C6LvfX4lnoWiz9KhLu"
    "QN5sfJFafz1BclGR8C16SFVC0QU7k1hNOMBFNDOdiIUA8tSbw+QyuknGpTud5ORpQXDozcGB"
    "G7Iar3rlvDrwCA4B6HQ7cm060+VvreOOdESXFNrozMV2utOLldGKXFs7axuAdlx6YoC2aWcu"
    "bmVUJtY2y+JZtmSWY88TL5nlzEcVz0w30v3h3GVaWa4/9hyCe00XarnSfm7PLNXF21CkhL9s"
    "Za3f1dJwravwt629WdALwwWZY8M59C3TGrfkBhu1mokMusFAjVWmZGqZGgeDoMv/+P4AYpKW"
    "+mrfaW0AAAAASUVORK5CYII=")

