#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

intro_scan = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IDCToRukZAAAAFmlUWHRDb21tZW50AAAAAABp"
    "bnRybyBzY2Fu154m+QAAAZpJREFUSMftVU1OwkAU/qaFgCRCie4I2JhodGGEE9jegBvQnoB6"
    "AziBcoLCCeAGU09AjQuNmggLXEFo4rp9LkoUZsrPThe8bzVvvn7z5ut7GWAffx8sKVmrsxsY"
    "qC6lPPj0MBxsFbjW4KDJtOTTKEAH94/BWoGrFprQttQcoPPUShC4rDJ3pehN4ZP97K8IXFi4"
    "k872WA8jADo1YEh13L50fwTOLLiSOfZr93d1bpHEgP3WBVTg1IJLEGC/d5e5M784prrAqRfH"
    "c5+dVNlQ0vZGpnxxnUsXAdUU6keQ0Iu3y60KVai88DzqyUzqsxIluGxOPKCk4yNeThgAlAxw"
    "mZqKkhsGAAWr2lHiH1VCL4SIqAoAn0HYDhEibMfUUJeZoceONeJSA3mzBBOPZBN9ZirTgMzI"
    "F8wxipb4edGKDIHlkzmN56Kg5Yd5ErAikbek/WFBW2rlQ41c1AUrPSxaGQ0mFj9g9lcg5HLO"
    "Ae2GnLNmyLJ6hmdoC3hW3zipaSPFU7QGPG3sNO6qrjoKV+YKLTBXuOqo+v4F+K/xDdyBCBDI"
    "VsksAAAAAElFTkSuQmCC")

