#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

power = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IBBl49y8AAAAAEWlUWHRDb21tZW50AAAAAABw"
    "b3dlcltxUw4AAAIWSURBVEjHlVXLbeMwEH2UjcC/GHIHMjYGgo0O3GwDdgX2dmB3EHegVKAW"
    "0oHsCpStwLrEQJANrOPexONiD5ocRFKUZMbKzIUcDmfePM5IgEXug59U6H2AT4SdN3OXZeXu"
    "wOwBuraDHO3EOW9OBKHU1gH80Cef/KBAUCoA+IFPPvmhlYPvLmLGizVNjuLOSPzCALWnBIuj"
    "aCC4dSkmrjIeRROBWhOn+NZtBKA419fzp3Ml5E96zymuBZiFxCVhgjavGwCok/i6oQ0pavks"
    "NDj4xtlB7gRbvCXF8sbg4I9kasYphoRPP94TiYBCnWurrjcRAMBbQlttlRjY1MNJnu9Ov8qs"
    "UwPByejEaYSVWp5SwMlXmt9ttROrJGpkW21fAYBDSwlpl6YVR0snpik9S/sSABz9fL/rs3Ae"
    "AZDv1XMCQJdUUyRVN/sEkPJ0AaCbf3kaqyeOqjMXtTyPmoPHOjaTmxKBW3X7GyBohSAXJiVt"
    "RNMuihISWcKydQD18EUrq0eh+cRrc33i0Vwi2BcIdprGsFX+cnJ20jSOxiR1fen6eK19I228"
    "5iOSmo0+pXLER5nyvTY9h+GQCh1kAyuKwXqQKb9hvdz+oU9ao16Dzp7XjwyPQ+Or3HMRwwBF"
    "z9jr6eBYsrn508Din2h81q9qIaySYPFf2P5zYZcu6KWn7vBO1CGLRp127e54zgOLWcZIasZi"
    "58Gx9OkH0fmIdMHE3EIAAAAASUVORK5CYII=")

