#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

reload_ensemble = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IFikm2m9/AAAAG2lUWHRDb21tZW50AAAAAABy"
    "ZWxvYWQgZW5zZW1ibGWwfIidAAAB8klEQVRIx81UTW7TQBT+Xpqowk3LJFlWFUEVqgBRVVyg"
    "4xPUN6hzA+cEmBMETuDewM0J8AmoAVEq1BKkKmubFbt5LDLj2LGdmG5gvo09+t73fucB//pQ"
    "1eVrARenkCQW/5wiwhSXH9MGAicCE3KrZDnFe7yL04znxX5J4NhBYPzWiIw+XwLHEiGJT7Qi"
    "8GoCb3PWPKYnC96XosDLonlMU0T6W/I5hmWpr3mB5w7CnPH4OiqSX0gOVkW+LQWOBGZZ7hcY"
    "31TU+0jSh+LNDQHtxaeakGBt/n1UlfkzT72hujk4FJSY4GHflrwfCgohy8a3JgJ22eiN7yqC"
    "Z49lXU9aAKBOFRQUVHwXVZF++GyrC5VqVoalgGQwGDyt8zOLfo74KY840kwweFmDA5OBfR9t"
    "GqODIVzoqbg3bdzPBOZRsze4L3GO4dzWRVR//YjnkZnSBwqsdsHUVz5QwNRWnTUxGfgDd1B8"
    "FX2vzwv0NsbQk5qZ9GXWRiGgR5lj2L/SevPHAldkvPfSJXMv2GONYJ3/Wt6u6CZd1gh2Kpfa"
    "jugGGSfZXeVYjsUZrqxSLSxpzXIMp2IrPyqsNI6RW2k4o5Oc2tvffmWG2/42N4C/pkgdp5N0"
    "eA2SjrOhz22xFWxxDYK2aDaeouVRSAmxRkJhy2sJ/JfnD4hD/RXfAbnfAAAAAElFTkSuQmCC")

