#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage
# --------------------------------------------------- #
# Some bitmaps for ribbon buttons

align_center = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAADpJ"
    "REFUKJFjZGRiZqAEMFGkm4GBgQWZ8//f3//EaGJkYmaEsyn1Ags2QVwuQbaZNi4YDYMRGwYU"
    "ZyYAopsYTgbXQz4AAAAASUVORK5CYII=")

#----------------------------------------------------------------------
align_left = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAADxJ"
    "REFUKJFjZGRiZqAEMFGkm4GBgYWBgYHh/7+//4lRzMjEzIghRqkX8LoAm430dQExLhoNg2ER"
    "BhRnJgDCqhhOM7rMkQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
align_right = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAADdJ"
    "REFUKJFjZGRiZqAEMFGkm4GBgQWb4P9/f/8To5mRiZmRkVIvYHUBsS6inQtGw2DEhQHFmQkA"
    "gowYTpdfxvkAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
aui_style = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAMFJ"
    "REFUWIXtlrENgzAUBQ/beAQWYAcGYYIkgyWZxz2lF0CiRwJBCmKJIlGq+DV+lS1ZutO39eSq"
    "MpaU5+O+kyGX661Ka3eG932fgw+wJwmTi/gtRcCdN9u2aQWWZdEKzPOsFVjXVSsguYJz++Wc"
    "QOI6gLZtAZimKQs88WKMh0CMMQv4UxxA0zQS+DiOh4D3XiIA7wkYo2tkB2Ct/XXuvwJ1XWsF"
    "5BOQv4FhGLQCXddJ4CEE/Y+oCBSBIlAEHByNpMoLu1w1qHGIod8AAAAASUVORK5CYII=")

#----------------------------------------------------------------------
auto_crop_selection = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAi5J"
    "REFUWIXFlz1r20AYx/+ns4PjR7jG1IgG2tIO/QAdkyyZOvcrlECnQujWT9AtFDIF+h06dcjU"
    "KaFTxg4dWwiIBNU1d8Y0Ol0H+8TpxUKKpOgPB7Is7vfoebtHjDkcXcrplA4AzOFYe0ED0Pd9"
    "zUwIdKQ0czhr/Y3XMjxWlAP3YVScAzpSOg0/9g8z95uS2Tc3CQ0cAE5vjuKH2zAmNsC42oYT"
    "d0Gc8OXvR+hI6TNx0pgRhpebhDpS+vTmCMQJ5LgAgOHamP3tN2giLwwvNwTM4eztw08ZOHG3"
    "LjejTAjs368ffEjAyaHGwIZXWAVn4qQVeIJnd0Jzne6O9ko/Q/vfM/fKLKQ7YVXRwaWeTAZw"
    "iUNIhSBYQn57WTk579SK6eBSP3lM2PG2MB71MJuHuPL/4ddvWdoIw+tVtRgAJpMBdrwtPH86"
    "gDftw7++BQAIqSAr7rWxCjZpuHuuXeIYj3rwpn28eLYNb9rHeNSDSxzD3fNSjcrwYg+UDcHi"
    "Yo+JRz/0bB7Gb+5f32I2DyGkwuJir/0QBMESV7TKneBPGOdAECwr79V5FRT2gTIrrw+gRP9A"
    "ug80NXzoSOmf4VcAgIwkpBKQSuKV+y6R6JnDqOnJpwhu8zaeBU3BF0rE84T9TOFEVNsAC74y"
    "SCQmK1uthMC43cClWnnEnjELJ6K6MnuZyUquPfHe+5wY/ZjDWe0yLHPsHvuHmVJE3eP4Lh7J"
    "+6+VKkgrD547EaHLb8Ou9B/kXYasrB2oNQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
auto_crop_selection_small = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAASRJ"
    "REFUOI2lkzFLw1AUhb+XdOvQiiAqgqAgLeJSWo0RG+iiOBRcXV3t6OIPEHfnQPUPFERxExRK"
    "i7gLXUSoo4hDxuQ62AsSQxPaAw8u7753OOdwrwGECWEs2+S0AJAoFK3TIFEoAJZerDhz0uo0"
    "kSgUbWZBTtkOTmtseRvM3y0y6A65vrjPRGCphcvDG957n3iNTfJ2PquAXwWKQXfIR/+Ll6dX"
    "AAqOL9/949RMxFg28VN02+KcvEnRbSf29Z+VxFhwfClVPPYbM5QqHgXHHxvqVArMqEj0qRnU"
    "dtelWi8ThAFX57cYyzY6M4kWFBpgtV7m6GyPtZ2lf2/GEiiCMODx4Znl7Vl02FIziPsFpNVp"
    "yqq7IJkziOPvrmhtmHIbzUjOxPgBMl93hZvH4+AAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
circle = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAANtJ"
    "REFUWIXNV8sSxCAIA/z/T67d0864PiBQ2ZpbHQkxlGKZpVAEtV53+yxSOMLDqIA+oQVUkCnA"
    "m9grRDKTIxxLAUhykcKI1RrXtARagJXQGzsIWBF433KU50fALCjaXiinoBujmHG0udQu+AeE"
    "KO/0Gtc35xkODIsbT29xvu/Ajs9tFLVe9+BAhv0a9/sl6BcySzJv90TLLYgUPq8ERDllWE7H"
    "3Ym8ECJ7Yj2FNmvOcIAozwVr0p51JbOCESGPL6UIUU/o2QsLQIkRaK6pXZB1KW1x/s8pKijq"
    "1gcd75B9JbWfpAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
circle_small = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHxJ"
    "REFUOI2lU0EOwCAIg/r/J6u7TKMVgWXcDG2paFVRxKrWal/PQFELpyzARC4WQjSVCYyZDtbG"
    "za6FQZbMvcHBDZARERFBtDSvWqt9OshMt7DwgCmx1U6WtC/9g/VjOoq6HymaLvJewXrfiDw4"
    "WxZuAfKC9TtMh0DkhusBDWJQP2fEFKMAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
colours = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAOklE"
    "QVQokWNgIBEwMjAwXJJiwpTQefgPU5CJlQGLUvxgRGpgYWBgiNiHReJu3H9s6hkHoR8GoQaS"
    "AQBoQQZvRwyakAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
cross = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAO9J"
    "REFUWIXNl9sOAyEIRIHu/39xU/epiXVRhltSX3ZNZOZoDCCzvGge4/MeLBdTw9C0ZV0wf6vN"
    "NW1ZF+zmFebaXE5mFRCWNhMN0yR6J5ANCCIeOQkkhuVi+f5UQqDmRNMlrILwmP8AVEB4zR8A"
    "GYiIuQoQgYiaExHxmop3Jplx2pB6AkhghbkJkIVAYk2AKAQaAwF4ITxrYYCuAQNUp2IXQFcx"
    "ggAyuQAqx13mqMYWAE2v2QKmAnhzewbiARAtLFEItS33mmcgtm151MALcWzLvcIRiP9vyzvL"
    "sdmWdzYkZlte+UI+aattecfzfKd9AzzryGWicE3pAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
empty = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAANElE"
    "QVQokWNgIBEwMjAw/P//H84/efIkHtUWFhZMpNpAew0sDKjuNjc3H2gnjWqgiQaSAQBRvgke"
    "qvN6jAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
expand_selection_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAVFJ"
    "REFUWIXtVjFuwzAMJCmjQGrv/UH27vlB9j4gyAvykC5eCz+gewbv3rvnB93lGihCsUNqQ1Ys"
    "x0nUJgZ8AGFapOgTKVFGJAW3BN306xOBURIQwyKGpU//UwIAAEgK66etXxRrdMewL83/VoKQ"
    "uL8SnNrN19i67OQ65Tr1070SuU6PSDYExLAUVdYiY0s93nfcbJtvflFlLRKIpEAMy8f3O5Ss"
    "oeQSvlhDaQ56yRo2T29NcDEsPhK2TQzL6+caYpVArGKIKYHHWlcJPD+8AJJCEsOy228HJjEc"
    "dvstiGE5+xgOLcFQEJLCebQcPCFUI5pHywNhJAW/vUCKKpNcpwIAR2L71borrp8ruU6lqLJW"
    "vKYESAoXsxXY77bY475VuX5d8xezVdvP7YR1Gofs9HNtXXGjvlWEhC/u/d0FpzBdx6ExzhL4"
    "/ooviTW+EkwEQuMHDB37+4Mc8HwAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
expand_selection_v = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAATtJ"
    "REFUWIXtlzGOwjAQRb8dhISCRMkN6OnpKaho9gArWho6TkBHQ4v2ADRbpaCnp88NtlyJCAnF"
    "HqqAozhoPfEmIPElS04cj59mbE9GCBmAK9KKAEDIQHBtyCqLx2mEOI1uIBwJjgdIKzpedrl3"
    "w/YHyxPOAKQVHc5f1rFR59MZwgmAtKL9afPwm3F37gThDJD1v39XubFpb3k36gDQ+vPqhmHS"
    "ihJ9Kh13kROAqUQl3Km+AIoe4Ih9DK3G6jiGvsW+Cb1JyKDQABAA+q9+rtlCQFpRlQRTJpvd"
    "59wDVbLbI9nsNr4J3yEoDUH2MWlFvvq2dZ4zBHWKlQ19JiN2Ol7/zHLPi/6WZYcNEAZd7lRf"
    "AGH9AGbsQ1n0AKdSeq3f8gyiscLEhGisNDMh4jQCAAxaE3aFXOkq9lGeXwGxGs15gJjjygAA"
    "AABJRU5ErkJggg==")

#----------------------------------------------------------------------
eye = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAJNJ"
    "REFUOI3NkjEOwjAQBOdsoE7pwj+gyCP4f0HBD67gDUHJUkRGhkRIlgtYyZJ13h3pzmcWIj0K"
    "Xem/ABw+C1pmfQtYiLYLKEF3ByDnDGlaH++nuq4aZBYiWmYVQx0ez0cArrfHG6R4CkTu/jqA"
    "SJPGiwSDYFjvadKet3uI3S1Y2cSGIbIZYq3Wb9wAWvX7Ve4GPAEieGRem+OF/wAAAABJRU5E"
    "rkJggg==")

#----------------------------------------------------------------------
hexagon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAALNJ"
    "REFUWIXt180NgCAMBlALG7ILU7gLGxo9aWL4a/uV6KE9Q/sAxUoU4vZlBGRyjuXMsZxIDtLs"
    "QK/ofiRaCuCuVgJhAWYrRnZkCJAm1kCaAPSMJfNfAMuHi5vvAbQGawtzIHduohCrAVaFZ5D9"
    "SFRdRKuK93JDN6FFOMABDnCAAyoA2mSOopX7H5/j0UAEImpIpBPRwkOAFmLWlEoTL2vLuRBN"
    "YRVgBln+a9aDIK8rBLCICxjaeOXhD450AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
msw_style = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAOhJ"
    "REFUWIVjZGRiZkAGU3c8+c9AQ5DtIcOIzGdBtzzaSoCW9jMw7HjyH9kRjLAQmLrjyf8oS37a"
    "Wg4Fy45/hIcESgj8+UcX+1EAigN+/x1gB/yjafIbdQARDvg/AA5gZGRiZpi648l/D31+BkZG"
    "whqoAf7/Z2DYcRGSFRl7Nj36H2QuQh+b0cC6k28YmAbEZiTAwsDAwPD0xfMBsp4V4gAJUfGB"
    "sf/hO4gD/vwdgDIYCgaHA778+DOwDvg7EEUgsgPoVgLhcgDjiHfAaBQMuANGo2DAQ+De6+8D"
    "5oABb5CMOgDaJBu4NAAAvuND/BvGPIIAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
position_left = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAExJ"
    "REFUKJHtkzEKwDAMA0/yx/z/P7XqVOiQDmmHLDEIBEKCGyy5yHmEDyeXACIX3YlcPP2dvQkI"
    "QEblqYFRuTuZGtgIG2EpguR/33gBsoRzDlCsBR0AAAAASUVORK5CYII=")

#----------------------------------------------------------------------
position_top = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAPCAYAAADtc08vAAAABHNCSVQICAgIfAhkiAAAAFJJ"
    "REFUKJHtkzEKwDAMA092H5b//ylRppRCpzhToTd50RljJEXi0U0BRQrAiqQ1W5HszIABXAkr"
    "kltQCb8E3z1By1Llev5zF4/uONkO8AtAp22caOhgKT6Nla4AAAAASUVORK5CYII=")

#----------------------------------------------------------------------
ribbon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAYxJ"
    "REFUOI19krtKA0EUhr8xMcYbRIJgk87KBSsRBK0UROMi6y3Wig+wpLQTLMUHsLNSBEVCIoKd"
    "gpAyEBBMISKIiDeSmLhqxiLuZrPjeqrhXH6+c/4RoiWAX2iGKQHyR9vCryf43+D4zBLWtwTw"
    "FRJeAs0wpbEQ5+4Jql8BIl1tTu385EARCXqHB0bihIKwuxH+zdZY2xQIIRibWgSQbpEWL1Jf"
    "j+S5VH/ryQp6ssLOuvS5gItAM0w5ObtMb1eRd6ueS221O0JVq41wKKhQOAT5o21xerzHQ7GV"
    "SGeDwI630ge1mlTuoKzQHQ5RsRppPVkhtdVOTcJb+UNZ4U8XVlfmuX385LX0xUu5UStkM4oL"
    "ioAtAqDP6Vzff3N1mXHW9PYqH0kzTDk0bhDpCJE63AdgQk/wWr+s/JdAM0zZPzzt4E7oCQDO"
    "Uvu4826RJhsHR+O8Ww3Pbx6KynqDo/EmkiYbcxdpYlFBIZtRBgvZDLGoIHeR/pvAFrHVNcOU"
    "sWi9r+Cp+d7AHbYTHnElfgAFJbH0Sf7mkQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
powerPanel = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHlJ"
    "REFUOI3tk8EOwzAIQx+w307Dtu9u3UsS9bamuc4Ski8GjIyZByvwJTVA20CAnvBXb5SZAHp/"
    "vla3ol9cx666FWEemAeZqc7vVmbKzAMdu8zDZqx3zThiW28KdSvydsip6VfN30LYUhJHDrof"
    "gEvibvHR4CmWv/EExjdqKKO2QxEAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
square = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAEdJ"
    "REFUWIXt1zEOACAIQ9FC9P4HNinOuhsGPyNLXxoWouRS42RnOABJGvcic8bLQHsdN9feAAAA"
    "AAAAAAAAAAAAAILf8HvABvIMCjlFTCZ2AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
triangle = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAALFJ"
    "REFUWIXVl0EOgCAMBFvq/39s8ERCyCKwIJY9EYG2M9GDqsGETbzvKCKiZsrWCHT3RaEHSPTl"
    "etsAq0INgIhZC+cZyEnVTPMvgLFwloGSHq1HLZxjoEaPno1YOMNAix7t9Vrwb6CXHp3pseDb"
    "wCg9Otuy4NcAS4/uvFnwaWCWHt2tWfBnYBU9qoEs+DKwmh7VKi34MfAVPaqZ9/JhYObPhk3q"
    "eb1t7ohKlO30eX5/Bx4qMXoN5ex1NgAAAABJRU5ErkJggg==")

power = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IBBl49y8AAAAAEWlUWHRDb21tZW50AAAAAABw"
    "b3dlcltxUw4AAAIWSURBVEjHlVXLbeMwEH2UjcC/GHIHMjYGgo0O3GwDdgX2dmB3EHegVKAW"
    "0oHsCpStwLrEQJANrOPexONiD5ocRFKUZMbKzIUcDmfePM5IgEXug59U6H2AT4SdN3OXZeXu"
    "wOwBuraDHO3EOW9OBKHU1gH80Cef/KBAUCoA+IFPPvmhlYPvLmLGizVNjuLOSPzCALWnBIuj"
    "aCC4dSkmrjIeRROBWhOn+NZtBKA419fzp3Ml5E96zymuBZiFxCVhgjavGwCok/i6oQ0pavks"
    "NDj4xtlB7gRbvCXF8sbg4I9kasYphoRPP94TiYBCnWurrjcRAMBbQlttlRjY1MNJnu9Ov8qs"
    "UwPByejEaYSVWp5SwMlXmt9ttROrJGpkW21fAYBDSwlpl6YVR0snpik9S/sSABz9fL/rs3Ae"
    "AZDv1XMCQJdUUyRVN/sEkPJ0AaCbf3kaqyeOqjMXtTyPmoPHOjaTmxKBW3X7GyBohSAXJiVt"
    "RNMuihISWcKydQD18EUrq0eh+cRrc33i0Vwi2BcIdprGsFX+cnJ20jSOxiR1fen6eK19I228"
    "5iOSmo0+pXLER5nyvTY9h+GQCh1kAyuKwXqQKb9hvdz+oU9ao16Dzp7XjwyPQ+Or3HMRwwBF"
    "z9jr6eBYsrn508Din2h81q9qIaySYPFf2P5zYZcu6KWn7vBO1CGLRp127e54zgOLWcZIasZi"
    "58Gx9OkH0fmIdMHE3EIAAAAASUVORK5CYII=")

tune = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IGA4dU/eaAAAAEGlUWHRDb21tZW50AAAAAAB0"
    "dW5lpUR7AgAAAlZJREFUSMedlEtuE0EQhr8eO1GEZNEWL4tHMkYQSEKUCReIZ5ddzAniOQHh"
    "BMAJLE5gs0Je2ZxgzAWwvUIILE8SRZF4KC2Bwm6KReyxJ5n4kfo31er6/66q7i71XFNXBZCA"
    "F5/bzGxq06fQ94NWPjnI0TiqwHUcDB0JaLaDSGBDRiLdTvM8eaPEDsULmlXedgIASxhF3Nb3"
    "1ntSkWI8RhCkFLbWiwBW2A6JsDskrxWe9aQs9shuDKKlvuaAJZ4EQ93VCsCqXi3ji51wchx1"
    "UAArBWCX0ll1X7wVjY8z1SV4aug/qQwkvnpPtUwn0VCjq+W+hFS/ectTZqHiy0dRFt+9x1Nl"
    "kRq6D3V2oVvL2jiAk7W7tWyNbXLjBayhK2Xxbd31wmpIiJTyla4J3dg1JyAqYalIHWjj7pul"
    "qJB9z55QSF/ggaalbABp4x6axaidh97iuHYG/RJkb/DmxBH/nj6ICrlfOTDihsElJTRTAHe1"
    "fGAhUs3JdqZ2VMv025nRRx8ziu3EDN5ZAFIUHXvnjvg5fTTIwoFLWmmkkQYIX6oLI0D8O+6x"
    "lzM4vIdwRyW+w2Oj4LZNLzG9trg/DcAtR/nohIj8jyANYeGSDjv0blb5xJbsSdJ+9VcACm68"
    "4fXssxBD/reBNIRbXMW8EwOQBrkKvWoaZ04awtnpbV4N3DSEwax05f4xIwLSmfF096+JfaZr"
    "tvRmOf3UnJsHp4E0J87fM1T/bcbpfZt35mUiTuaLYzKbK6VlLMpzetJwLKR6KUnASaqSsqfq"
    "j6WtkvKVRGipilWcxPoP2ziIkLGGTBwAAAAASUVORK5CYII=")

seek_prev = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0ICCSMKiwdAAAAFWlUWHRDb21tZW50AAAAAABz"
    "ZWVrIHByZXbYj/91AAABEUlEQVRIx+1SQW7CMBBcR2k4gaL2XBEkVCFViMAP+AH8gCfwE/hB"
    "+EF4SZMnVOq5AbW9ercHmjR21rEVrpm5WJ71eLxegB53Q5SLVQZxbT9/W3LlqwPsVa0yiEkt"
    "zYV+eBGJ9HZJXfPLBVqizjeYiLC5XxnI1uOvB9zzikOCWSRSjE2q1eDFEN3xCVNjdIcEk9bo"
    "VoOxJXpjDp7Jffo+usxB519wNpAdDbz/BCppi1cEnmwTH7UmFuIpohTYbywEk0BqBPh8L5Z4"
    "lCAZjUkw1BJ8/ymjDSUQ8lprD0p8nWmNubkHVgOAnxzXeDIZVAhIpa4PdsHFpN0GglQ2Kx5i"
    "PzNpAOBlHtWYsTWhl5i0HnfgF4onpngBY0G/AAAAAElFTkSuQmCC")

seek_next = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0ICTcRj1yCAAAAFWlUWHRDb21tZW50AAAAAABz"
    "ZWVrIG5leHRgQmccAAABBElEQVRIx+2VQQ6CMBBFW4K6Je6NaIzRGJPqSeAGcgM5id5Ab6An"
    "cfAGJm5NxLhwxYwLCcWmBUSX/r8Bpn3MZ5rA2F9fi8vLOTDB1odQt2wOTORuo8NMAxD0KpJ/"
    "PKmAtCYJ2T5LPsSXBcLUUwGoWCoHSFKjg7vJ6h2QKNYC3t6xHMPI/bADZZFAGHq1IuSjDFZ1"
    "I2RR+tBzizqw8wCtBEE3wCoHqUPVz9+ZV++gRL8EJLUAZVNgyDAm/5spRNy/nNp1I/B1HBbH"
    "K+og5sFtX/aBzYCIB/eofEImwJaFj/jDETcp9bW1MNZS65shm2yyoSGMtcz6IwEWWRvLMdak"
    "4f83+qmeWZTQvV9JdZEAAAAASUVORK5CYII=")

scan = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0ICwySstckAAAAEGlUWHRDb21tZW50AAAAAABz"
    "Y2FuMHJZPgAAAiBJREFUSMftVcFu00AQfZukatIm6jpqq0qWwFRNoUIo7hfg3DjmyA3nC+rc"
    "uLX5gqRfkP5B0hNHhy+wEUIFCdVWzyh2xKUc1sPBm3UMCeEGh85cvG9Wb97OzqyBB/v3xpbD"
    "p232EhbMBWgCn95747UETQ4HZ4wvJ6YYlxh8iFcSvLjAGfga1TEuP14sITgx2TATzSa4xuST"
    "n66emzDxhiy12afOjZ8jeGajr3Jfsd5NCABPDRgAwi8hAJwYdA5b6eh+vlKEDbtB0oNjmeeI"
    "N0YKHR5J8mOr4SnUlgoObTZUubtfYwA45MzN3YJPrds4Jab+XAd1isBjE+8IBAJ6t93pfRra"
    "eUuvU1T6Af2IJwAwvY+u+Sx5RSBQmwGPAhgAgM5ddqYMHYDLfOHdk4W4jblqnXTSSXfydyVR"
    "DwB0L139ssPRSacSkKSnaebDKQrjwAISU9Y9Z6LJABQAMREQSOz90d5CC4mxgIDgiZu4AgIC"
    "YqGN9/j+KLEFBBiwy2leb59aU5ln1yQv33/s9FuYftazG/IloHkaaaSRFnHVbfW2FkmUtKiu"
    "cG4p3Ktz2Yk7mQpgQL3vcYrCBgcQYjyLAaDG2Tnm5fZZa5bVpcaroypJD7btZVO0bVcDtWdU"
    "+33otpwKKQ8q/bKSXbYq/UqQRbecFZNaNjbdTVrjbtn447hvWCW3RCvc3bD+6qUrGkWn4Bai"
    "AkmPCm7RKRoP/4D/034CO5kLFwuqGtQAAAAASUVORK5CYII=")

intro_scan = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IDCToRukZAAAAFmlUWHRDb21tZW50AAAAAABp"
    "bnRybyBzY2Fu154m+QAAAZpJREFUSMftVU1OwkAU/qaFgCRCie4I2JhodGGEE9jegBvQnoB6"
    "AziBcoLCCeAGU09AjQuNmggLXEFo4rp9LkoUZsrPThe8bzVvvn7z5ut7GWAffx8sKVmrsxsY"
    "qC6lPPj0MBxsFbjW4KDJtOTTKEAH94/BWoGrFprQttQcoPPUShC4rDJ3pehN4ZP97K8IXFi4"
    "k872WA8jADo1YEh13L50fwTOLLiSOfZr93d1bpHEgP3WBVTg1IJLEGC/d5e5M784prrAqRfH"
    "c5+dVNlQ0vZGpnxxnUsXAdUU6keQ0Iu3y60KVai88DzqyUzqsxIluGxOPKCk4yNeThgAlAxw"
    "mZqKkhsGAAWr2lHiH1VCL4SIqAoAn0HYDhEibMfUUJeZoceONeJSA3mzBBOPZBN9ZirTgMzI"
    "F8wxipb4edGKDIHlkzmN56Kg5Yd5ErAikbek/WFBW2rlQ41c1AUrPSxaGQ0mFj9g9lcg5HLO"
    "Ae2GnLNmyLJ6hmdoC3hW3zipaSPFU7QGPG3sNO6qrjoKV+YKLTBXuOqo+v4F+K/xDdyBCBDI"
    "VsksAAAAAElFTkSuQmCC")

cancel = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IERlPQskUAAACKklEQVRIx7WUwWoUQRCGv541"
    "GDTZ9AZBCSGsRAIiSsc3mCfIPsLOE2TzBMGTxzVPMPMGa46e1ieQQRFZSGIIAUkQpi+KHjLl"
    "YZZJ987EnSBOnbr6r7/rr6op+MdP1Tlfdumxg1G6OIsl5ZC3H04bEBjDvurVvybv2UvTvxC8"
    "0GqfwZyc38irj7aW4LlmjGkgOyX8ZCsEzzRjZZoVTlLCz9YjeKpVs9fLLCT8YgFaxfnBa+kJ"
    "t7BHLH5/BxAAbBkZeNdWtiXxPIlsi/U8gy1TEsgwxzGbh5N0EuVJ6Ukm0STNw9y6ONmf1mCz"
    "y1dHnVXh0bTXmzF9IDmOivMTI2O0g318fBpA7qsvw+E4kkTKcDhKJXSxeQ8CkB03satdt9gn"
    "0Unknq92PRE7oGAj89KC5Cyq791GIcmRe9ZRsC4VZHJeQ7E+Gw6cq4C6LvfX4lnoWiz9KhLu"
    "QN5sfJFafz1BclGR8C16SFVC0QU7k1hNOMBFNDOdiIUA8tSbw+QyuknGpTud5ORpQXDozcGB"
    "G7Iar3rlvDrwCA4B6HQ7cm060+VvreOOdESXFNrozMV2utOLldGKXFs7axuAdlx6YoC2aWcu"
    "bmVUJtY2y+JZtmSWY88TL5nlzEcVz0w30v3h3GVaWa4/9hyCe00XarnSfm7PLNXF21CkhL9s"
    "Za3f1dJwravwt629WdALwwWZY8M59C3TGrfkBhu1mokMusFAjVWmZGqZGgeDoMv/+P4AYpKW"
    "+mrfaW0AAAAASUVORK5CYII=")

reload_ensemble = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IFikm2m9/AAAAG2lUWHRDb21tZW50AAAAAABy"
    "ZWxvYWQgZW5zZW1ibGWwfIidAAAB8klEQVRIx81UTW7TQBT+Xpqowk3LJFlWFUEVqgBRVVyg"
    "4xPUN6hzA+cEmBMETuDewM0J8AmoAVEq1BKkKmubFbt5LDLj2LGdmG5gvo09+t73fucB//pQ"
    "1eVrARenkCQW/5wiwhSXH9MGAicCE3KrZDnFe7yL04znxX5J4NhBYPzWiIw+XwLHEiGJT7Qi"
    "8GoCb3PWPKYnC96XosDLonlMU0T6W/I5hmWpr3mB5w7CnPH4OiqSX0gOVkW+LQWOBGZZ7hcY"
    "31TU+0jSh+LNDQHtxaeakGBt/n1UlfkzT72hujk4FJSY4GHflrwfCgohy8a3JgJ22eiN7yqC"
    "Z49lXU9aAKBOFRQUVHwXVZF++GyrC5VqVoalgGQwGDyt8zOLfo74KY840kwweFmDA5OBfR9t"
    "GqODIVzoqbg3bdzPBOZRsze4L3GO4dzWRVR//YjnkZnSBwqsdsHUVz5QwNRWnTUxGfgDd1B8"
    "FX2vzwv0NsbQk5qZ9GXWRiGgR5lj2L/SevPHAldkvPfSJXMv2GONYJ3/Wt6u6CZd1gh2Kpfa"
    "jugGGSfZXeVYjsUZrqxSLSxpzXIMp2IrPyqsNI6RW2k4o5Oc2tvffmWG2/42N4C/pkgdp5N0"
    "eA2SjrOhz22xFWxxDYK2aDaeouVRSAmxRkJhy2sJ/JfnD4hD/RXfAbnfAAAAAElFTkSuQmCC")