#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

scan = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0ICwySstckAAAAEGlUWHRDb21tZW50AAAAAABz"
    "Y2FuMHJZPgAAAiBJREFUSMftVcFu00AQfZukatIm6jpqq0qWwFRNoUIo7hfg3DjmyA3nC+rc"
    "uLX5gqRfkP5B0hNHhy+wEUIFCdVWzyh2xKUc1sPBm3UMCeEGh85cvG9Wb97OzqyBB/v3xpbD"
    "p232EhbMBWgCn95747UETQ4HZ4wvJ6YYlxh8iFcSvLjAGfga1TEuP14sITgx2TATzSa4xuST"
    "n66emzDxhiy12afOjZ8jeGajr3Jfsd5NCABPDRgAwi8hAJwYdA5b6eh+vlKEDbtB0oNjmeeI"
    "N0YKHR5J8mOr4SnUlgoObTZUubtfYwA45MzN3YJPrds4Jab+XAd1isBjE+8IBAJ6t93pfRra"
    "eUuvU1T6Af2IJwAwvY+u+Sx5RSBQmwGPAhgAgM5ddqYMHYDLfOHdk4W4jblqnXTSSXfydyVR"
    "DwB0L139ssPRSacSkKSnaebDKQrjwAISU9Y9Z6LJABQAMREQSOz90d5CC4mxgIDgiZu4AgIC"
    "YqGN9/j+KLEFBBiwy2leb59aU5ln1yQv33/s9FuYftazG/IloHkaaaSRFnHVbfW2FkmUtKiu"
    "cG4p3Ktz2Yk7mQpgQL3vcYrCBgcQYjyLAaDG2Tnm5fZZa5bVpcaroypJD7btZVO0bVcDtWdU"
    "+33otpwKKQ8q/bKSXbYq/UqQRbecFZNaNjbdTVrjbtn447hvWCW3RCvc3bD+6qUrGkWn4Bai"
    "AkmPCm7RKRoP/4D/034CO5kLFwuqGtQAAAAASUVORK5CYII=")

