#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

seek_prev = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0ICCSMKiwdAAAAFWlUWHRDb21tZW50AAAAAABz"
    "ZWVrIHByZXbYj/91AAABEUlEQVRIx+1SQW7CMBBcR2k4gaL2XBEkVCFViMAP+AH8gCfwE/hB"
    "+EF4SZMnVOq5AbW9ercHmjR21rEVrpm5WJ71eLxegB53Q5SLVQZxbT9/W3LlqwPsVa0yiEkt"
    "zYV+eBGJ9HZJXfPLBVqizjeYiLC5XxnI1uOvB9zzikOCWSRSjE2q1eDFEN3xCVNjdIcEk9bo"
    "VoOxJXpjDp7Jffo+usxB519wNpAdDbz/BCppi1cEnmwTH7UmFuIpohTYbywEk0BqBPh8L5Z4"
    "lCAZjUkw1BJ8/ymjDSUQ8lprD0p8nWmNubkHVgOAnxzXeDIZVAhIpa4PdsHFpN0GglQ2Kx5i"
    "PzNpAOBlHtWYsTWhl5i0HnfgF4onpngBY0G/AAAAAElFTkSuQmCC")

