#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

seek_next = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0ICTcRj1yCAAAAFWlUWHRDb21tZW50AAAAAABz"
    "ZWVrIG5leHRgQmccAAABBElEQVRIx+2VQQ6CMBBFW4K6Je6NaIzRGJPqSeAGcgM5id5Ab6An"
    "cfAGJm5NxLhwxYwLCcWmBUSX/r8Bpn3MZ5rA2F9fi8vLOTDB1odQt2wOTORuo8NMAxD0KpJ/"
    "PKmAtCYJ2T5LPsSXBcLUUwGoWCoHSFKjg7vJ6h2QKNYC3t6xHMPI/bADZZFAGHq1IuSjDFZ1"
    "I2RR+tBzizqw8wCtBEE3wCoHqUPVz9+ZV++gRL8EJLUAZVNgyDAm/5spRNy/nNp1I/B1HBbH"
    "K+og5sFtX/aBzYCIB/eofEImwJaFj/jDETcp9bW1MNZS65shm2yyoSGMtcz6IwEWWRvLMdak"
    "4f83+qmeWZTQvV9JdZEAAAAASUVORK5CYII=")

