#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

tune = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAABOwAAATsAYpu/XIAAAAHdElNRQfeCB0IGA4dU/eaAAAAEGlUWHRDb21tZW50AAAAAAB0"
    "dW5lpUR7AgAAAlZJREFUSMedlEtuE0EQhr8eO1GEZNEWL4tHMkYQSEKUCReIZ5ddzAniOQHh"
    "BMAJLE5gs0Je2ZxgzAWwvUIILE8SRZF4KC2Bwm6KReyxJ5n4kfo31er6/66q7i71XFNXBZCA"
    "F5/bzGxq06fQ94NWPjnI0TiqwHUcDB0JaLaDSGBDRiLdTvM8eaPEDsULmlXedgIASxhF3Nb3"
    "1ntSkWI8RhCkFLbWiwBW2A6JsDskrxWe9aQs9shuDKKlvuaAJZ4EQ93VCsCqXi3ji51wchx1"
    "UAArBWCX0ll1X7wVjY8z1SV4aug/qQwkvnpPtUwn0VCjq+W+hFS/ectTZqHiy0dRFt+9x1Nl"
    "kRq6D3V2oVvL2jiAk7W7tWyNbXLjBayhK2Xxbd31wmpIiJTyla4J3dg1JyAqYalIHWjj7pul"
    "qJB9z55QSF/ggaalbABp4x6axaidh97iuHYG/RJkb/DmxBH/nj6ICrlfOTDihsElJTRTAHe1"
    "fGAhUs3JdqZ2VMv025nRRx8ziu3EDN5ZAFIUHXvnjvg5fTTIwoFLWmmkkQYIX6oLI0D8O+6x"
    "lzM4vIdwRyW+w2Oj4LZNLzG9trg/DcAtR/nohIj8jyANYeGSDjv0blb5xJbsSdJ+9VcACm68"
    "4fXssxBD/reBNIRbXMW8EwOQBrkKvWoaZ04awtnpbV4N3DSEwax05f4xIwLSmfF096+JfaZr"
    "tvRmOf3UnJsHp4E0J87fM1T/bcbpfZt35mUiTuaLYzKbK6VlLMpzetJwLKR6KUnASaqSsqfq"
    "j6WtkvKVRGipilWcxPoP2ziIkLGGTBwAAAAASUVORK5CYII=")

